#pragma once
#ifndef __HARDCODEDDATA_H__
#define __HARDCODEDDATA_H___

#define NUM_THREADS 13
#define TIMEOUT_IN_MILLISECONDS 5000
#define BRUTAL_TERMINATION_CODE 0x55
#define MAX_FILNAME_LENGTH 13
#define FINAL_FILENAME_LENGTH 20
#define ERROR_CODE ((int)(-1))

#define ID_STR_LENGTH 10
#define MAX_NUM_STUDENTS 10

#endif // __HARDCODEDDATA_H___