#pragma once
#ifndef __HARDCODEDDATA_H__
#define __HARDCODEDDATA_H___

#define TIMEOUT_IN_MILLISECONDS 5000
#define BRUTAL_TERMINATION_CODE 0x55
#define ERROR_CODE ((int)(-1))

#define ID_STR_LENGTH 10
#define MAX_NUM_STUDENTS 10
#define COMMAND_LINE_EXTENSION 25
#define FINAL_GRADES_FILE_EXTENSION 19
#define ID_FILE_EXTENSION 18

#endif // __HARDCODEDDATA_H___